### ISSUE TITLE
get pie chart spec to work w/ vega v1.5+

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#103]
Currently the site is using vega 1.4.3  so that the pie charts will work. If bumped to v1.5.0, everything worked *except* pie charts.

![error](https://cloud.githubusercontent.com/assets/5304673/7947265/e44acf4a-0930-11e5-9b89-54cfa2fe9f95.png)

See #97 for error message.

**Comment by ajturner** [comment]
upgraded to vega2 - and pie works.

The issue here was that `Math.cos()` changed to just `cos()`
