### ISSUE TITLE
Design for pie charts

### ISSUE THREAD

**Issue by ajturner** [Esri/cedar#109]

**Comment by ddred11** [comment]
![piechartspecs](https://cloud.githubusercontent.com/assets/5332496/8712768/32d26d98-2b15-11e5-968f-529e7ccebd33.jpg)

**Comment by ajturner** [comment]
So no legend or labels?

I'll see about the 'section magnification'

**Comment by ddred11** [comment]
I will add one more state with a legend , I do think that is necessary. Do we also need a printable version? That show value and labels?

**Comment by ajturner** [comment]
Printable in a future version - 

I'm also dubious of tooltips in general. It hides the data - so I can't read the chart at a glance.

**Comment by ddred11** [comment]
Perhaps lines pointing to a slice with the data outside of the pie in addition to the legend. When you rollover, the lines and data for the whole pie fade away and show the tooltip for just that slice?

**Comment by ajturner** [comment]
Admin Dashboard uses less lines. I'll ask @olearydw what his layout algorithm is
