### ISSUE TITLE
Update package version and tag release

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#116]
This is needed for #102 - specifically, we'll need a release that includes 7706a17f068fe2ee3a7531d6ea92c407978a6b99

It's been a while since the version was last bumped (852d28d1149a1a42b147f2a750de82c0d2dd2b0b) so I have no idea what to tag the latest. I'm also not sure which (if any) of all the many commits since then are worthy of being tagged as a release.

One idea is to just call whatever gets done under the 3.14 milestone as v1.0.0?

**Comment by benstoltz** [comment]
Package version / tags up to date now. Closing.
