### ISSUE TITLE
Question: where to embed HTML/CSS for tooltips

### ISSUE THREAD

**Issue by ajturner** [Esri/cedar#129]
Tooltips and other features like [sparklines](https://github.com/Esri/cedar/pull/128) will require some CSS to be added to the page. 

Where is the best place to have Cedar hold and inject these?

**Comment by dbouwman** [comment]
@ajturner css being css, there is no "best" place for this.

We can inject styles via javascript, but that's perilous and a pain to manage css rules as code, and its really hard for people to edit the styles that way (they can override, but there are perf costs to that)

Thus, we should follow the lead of Bootstrap...

Technically, the best option is to use a pre-processor, and have people include the "component" styles as needed using a build process. 

But not everyone wants to use a build process, so we likely also need to ship a big "all-the-things" css file as well.

**Comment by ajturner** [comment]
@dbouwman independent of how it's built - foremost thinking about the developer experience so they "don't have to think" 

If I understand - we can manage as a CSS file - then the build would wrap these as JS strings that are injected at boot up?

**Comment by codylawson** [comment]
From a styling standpoint its very annoying overwriting inline/js injected styles. They have the maximum specificity and require `!important` to override. Might be nice to use a css preprocessor like sass/stylus and have files for axis, tooltip, legend etc. already compiled to css for people who don't want to futz with it, but still available for others to customize.

**Comment by ajturner** [comment]
Implemented first version of this. Can be improved later
