### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by HeikoH** [Esri/cedar#130]
This https://github.com/Esri/cedar/commit/3714667fd3930607579e2fc450dddb99cbf0755d broke several examples (the ones that don't have `x` and `y` in `mappings`, e.g. time and pie)

**Comment by HeikoH** [comment]
Actually this https://github.com/Esri/cedar/commit/04977d42aadf5d138b310baf8e5f6378a2d1845e#diff-5c0b5aaebca2221437b2e4cd644fb985R251 is the one... Previously `autolabels` was `false` when not explicitly set to `true`, now it's `true' when not specified.

**Comment by ajturner** [comment]
Thanks - I should have marked the PR as DNM. Didn't know @benheb was so attentive!

**Comment by benheb** [comment]
Ooops! I looked :+1: to me!

**Comment by ajturner** [comment]
reverted that default change.

Time to add tests...
