### ISSUE TITLE
Create scatterplot matrix (trellis) demo with health data

### ISSUE THREAD

**Issue by ajturner** [Esri/cedar#134]
Given ArcMap scatterplot matrix:
![image001](https://cloud.githubusercontent.com/assets/1218/8639518/6cbff84e-28aa-11e5-88a9-d5e0589746b3.png)

Recreated with Cedar (Vega) - http://jsfiddle.net/c5fc3vb3/2/ (or [bl.ocks.org](http://bl.ocks.org/ajturner/cce66de24a9d7df8b1a5))

<img width="770" alt="localhost_8000_cms_medicare_html" src="https://cloud.githubusercontent.com/assets/1218/8639571/f5f69d2e-28ab-11e5-82e6-349a8f4542ce.png">

@phlorah

**Comment by ajturner** [comment]
this was a quick example using the Vega example scatter matrix. It should be possible to only show half the plots and add a histogram for the univariate 'comparison'.

I didn't have the specific bin values from the choropleth, so this just uses an equal interval for the demo.

**Comment by phlorah** [comment]
Awesome!!!  
Aesthetically it needs some work, but it's great to see a scatter plot matrix created from real data :)

I want to clear one thing up though - a scatter plot matrix is not the same thing as a trellis of scatter plots.  A scatter plot matrix tries different combinations of variables:

![image](https://cloud.githubusercontent.com/assets/5804042/8640139/f5f20d80-28a2-11e5-8848-41804026621b.png)
 
While a trellis of scatter plots visualizes the same 2 variables over different categories:
![image](https://cloud.githubusercontent.com/assets/5804042/8640144/1fc27348-28a3-11e5-8bf4-a81b7d019a54.png)

A trellis can be made of any chart type.

**Comment by ajturner** [comment]
Ah - thanks for the clarification on Matrix vs Trellis. I thought they were interchangeable.

**Comment by simongis** [comment]
This could be very relevant to a project we are working on. 
Looking at the fiddle I get an error in the console when trying to run it
_Failed to load resource: net::ERR_BLOCKED_BY_CLIENT_

Is this just me?

**Comment by jgravois** [comment]
@simongis i don't see that error in the console, but nothing draws.

the only difference between the fiddle @ajturner posted and the [bl.ock](https://bl.ocks.org/ajturner/cce66de24a9d7df8b1a5) is that the fiddle is missing the statement that actually paints the chart to the DOM.

```js
vg.parse.spec(spec, function(chartCtor) {
  chart = chartCtor({el: "#chart"}).update()
});
```

here's a corrected fiddle: http://jsfiddle.net/x8dxexqq/
