### ISSUE TITLE
Travis is not running the tests

### ISSUE THREAD

**Issue by chelm** [Esri/cedar#149]
I am not trusting the travis.ci build checks after pulling master and seeing code that would have broken the tests on travis

If you look at the output in travis I do not see a call to `npm test` https://travis-ci.org/Esri/cedar/builds/71819113

What am I missing?

**Comment by chelm** [comment]
the travis.yml file is just deploying to gh-pages? https://github.com/Esri/cedar/blob/develop/.travis.yml#L12

**Comment by benstoltz** [comment]
Travis runs tests now, closing issue out.
