### ISSUE TITLE
provide versioned minified build

### ISSUE THREAD

**Issue by HeikoH** [Esri/cedar#153]
maybe add cedar.min.js to the root and update on every release?

**Comment by ajturner** [comment]
@HeikoH so is it easy enough for you to get a RawGit file to a tagged min? 

for example: https://rawgit.com/Esri/cedar/v0.2/src/cedar.js

but to a `cedar.min.js` as you point out? 

curious if @dbouwman or @tomwayson or @benheb know other common patterns here.

**Comment by ajturner** [comment]
https://rawgit.com/Esri/cedar/v0.3/cedar.min.js
