### ISSUE TITLE
Cross origin request error when running Bar Chart sample from disk

### ISSUE THREAD

**Issue by azhigimont** [Esri/cedar#159]
When I run Bar Chart's sample html doc directly from disk I have the next error:

*XMLHttpRequest cannot load file:///C:/temp/cedar/src/charts/bar.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.*

Is it possible to use relative path to avoid the error?
For example, the next statement
```javascript
    var data = $.getJSON(C:/temp/cedar/data/temp.json ...
```
fails with a similar error, while
```javascript
    var data = $.getJSON(/data/temp.json ...
```
works fine.

**Comment by ajturner** [comment]
You can pass in a URL for type. So can you try `new Cedar({type: '/data/bar.json'})`

**Comment by azhigimont** [comment]
Unfortunately, it doesn't work. Still restores a relative path to an absolute one.

**Comment by azhigimont** [comment]
After some research this just shouldn't work. Also I can't repro the case I claimed to be working.  I will pass specification from the app. Closed!
