### ISSUE TITLE
Integer values on y-axis being labeled with decimal places

### ISSUE THREAD

**Issue by apfister** [Esri/cedar#166]
How can this be controlled to show only integers? I've double checked and the values i'm passing in do not contain decimal places.

<img width="962" alt="screen shot 2015-10-04 at 3 12 50 pm" src="https://cloud.githubusercontent.com/assets/5233042/10270002/becc0802-6aaa-11e5-84f5-a62be4316e1b.png">

**Comment by apfister** [comment]
can you give me a pointer as to where this is set or overridden?

**Comment by ajturner** [comment]
This is in the Vega declarative doc I believe.

**Comment by apfister** [comment]
@ajturner can you take a look at the fiddle below.

I've looked at the Vega doc for formatting (https://github.com/mbostock/d3/wiki/Formatting#numbers but when I include the "f" format option for the y-axis, it jacks up the other x-axis.

http://jsfiddle.net/nv7j4m0z/6/

![screen shot 2015-11-02 at 7 47 21 am](https://cloud.githubusercontent.com/assets/5233042/10883199/fac704c8-8135-11e5-8ef6-1a29a8ed451d.png)
)

**Comment by ajturner** [comment]
this works. note it's order specific right now, so you need a placeholder `{}` for the x-axis.

```javascript
  chart.override = {
    axes: [{},
        {
            "format" : "01d"
        }
    ]  
  };
```

you can also customize the X axis

```javascript
  chart.override = {
    axes: [{"properties":{"labels":{"angle":{"value": 0}, "align":{"value": "center"}}}},
        {
            "format" : "01d"
        }
    ]  
  };
```

**Comment by apfister** [comment]
got it. so for the sake of being complete:

The current docs that reference this are here:
- Under `Inputs` mentioning the `required` elements
  - http://esri.github.io/cedar/api/json/specification-json.html
- Then in the chart spec (bar.json, for example here)
  - https://github.com/Esri/cedar/blob/develop/src/charts/bar.json#L2-L5

the only thing i don't see anywhere is that the order of the overrides is specific. **must** be x, then y

**Comment by ajturner** [comment]
@apfister it's not necessary `x then y` but `the order of elements in the specification`. 

It _just so happens_ that _bar.json_ has the axes in [{x},{y}] - but if it were [{x},{color},{y}] then that would change the overrides. 

Internally cedar is doing a deep-nested [`Object.assign()'](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) that merges the two objects.

**Comment by apfister** [comment]
dig. :+1:
