### ISSUE TITLE
Pie Charts not rendering

### ISSUE THREAD

**Issue by apfister** [Esri/cedar#169]
http://esri.github.io/cedar/examples/simple-pie.html

Error msg in dev console : Uncaught TypeError: Cannot read property '0' of undefined

**Comment by apfister** [comment]
i've forked the repo but i'm not sure where to start looking into this. it looks like the error happens here, https://github.com/Esri/cedar/blob/develop/src/cedar.js#L555. `axes` is undefined when it's a Pie Chart. other chart types will come in with `axes` defined.

@ajturner - can you point me in the right direction? do we need to update any dependencies?

**Comment by ajturner** [comment]
I haven't looked at it yet. But that error typically means that the data are not loaded or addressed correctly. 

It would be good to look at the pie.json definition.

**Comment by ajturner** [comment]
PR submitted, waiting for tests.
