### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by calleja23** [Esri/cedar#171]
Hi guys,

Thanks for your work.

I have a problem when i load ( <script type="text/javascript" src="//esri.github.io/cedar/js/d3.min.js"></script>

<script type="text/javascript" src="//esri.github.io/cedar/js/vega.js"></script>

<script type="text/javascript" src="//esri.github.io/cedar/js/cedar.js"></script>).

the problem  is: NetworkError: 404 Not Found - http://js.arcgis.com/3.13compact/cedar.js"

Thanks advance

**Comment by calleja23** [comment]
![error_cedar1](https://cloud.githubusercontent.com/assets/11317014/11280564/d6fb9a80-8ef6-11e5-965f-876b4e8dc796.png)
![librerias_cargadas](https://cloud.githubusercontent.com/assets/11317014/11280565/d73801e6-8ef6-11e5-9557-1cb46e8a9a01.png)
![require](https://cloud.githubusercontent.com/assets/11317014/11280566/d75ee842-8ef6-11e5-8422-483a07fee13c.png)

**Comment by ajturner** [comment]
this looks like it's a problem with Dojo and the JSAPI. can you share the entire HTML as a Gist or other link?

Also follow this example: http://esri.github.io/cedar/examples/map-to-chart-interaction.html

**Comment by tomwayson** [comment]
@calleja23 do you have a "cedar" entry in your `dojoConfig` packages? If so can you share? If not you need one.

@ajturner I thought we had documented the need for that^^^ somewhere in the site, but I didn't see it after a quick glance around.

The site's dojo config is:

```html
<!-- define packages for Cedar.js and dependencies (d3, Vega) for dojo loader -->
    <script>
      window.dojoConfig = {
        async: true,
        packages: [
          {
            name: 'd3',
            location: 'http://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5',
            main: 'd3.min'
          }, {
            name: 'topojson',
            location: 'http://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19',
            main: 'topojson.min'
          }, {
            name: 'vega',
            location: 'http://vega.github.io/vega/',
            main: 'vega.min'
          }, {
            name: 'cedar',
            location: window.location.pathname.substring(0, window.location.pathname.lastIndexOf('/')) + '/../js',
            main: 'cedar'
          }
        ]
      };
    </script>
```

I can add a page to the docs explaining how to configure that so the dojoLoader knows how to load cedar and deps and then link to it from all the pages that do that.

**Comment by ajturner** [comment]
Thanks @tomwayson. Adding that to the docs would be extremely helpful.

**Comment by tomwayson** [comment]
OK, so I knew I had added it somewhere, it's in the [Loading Cedar section of the README](https://github.com/Esri/cedar#loading-cedar). Do you think it's worth adding the contents of that section to some place in the docs? The tutorial page? Otherwise I can just link the AMD examples to the README.

**Comment by ajturner** [comment]
Probably worth linking from the Esri map example.

Then the details in the docs. While I prefer README if devs land on ghpage they likely won't see README
