### ISSUE TITLE
Be explicit about the versions of vega and d3 this depends on

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#172]
It's unclear about the version of vega that is required for either the develop branch, or the releases.

Places where this should be 
- bower.json dependencies ~~(vega may be only dependency needed, which in turn will decalre it's dependency on d3)~~
- README [Loading Cedar](https://github.com/Esri/cedar#loading-cedar) and [Dependencies](https://github.com/Esri/cedar#dependencies) sections
- [release notes](https://github.com/Esri/cedar/releases)
- [varios places in the docs](https://www.google.com/search?q=vega+site%3Aesri.github.io%2Fcedar%2F&oq=vega+site%3Aesri.github.io%2Fcedar%2F&aqs=chrome..69i57.7382j0j4&sourceid=chrome&ie=UTF-8)

**Comment by jgravois** [comment]
is the version listed in the [package.json](https://github.com/Esri/cedar/blob/master/package.json#L63) not trustworthy?

**Comment by tomwayson** [comment]
ooops... didn't even see that.

I still think it should be in the other places too.

**Comment by tomwayson** [comment]
w/r/t to bower.json and package.json, I suppose both need to explicitly declare a dep on d3 too b/c it's used directly by the cedar code. Updating the title of this issue to reflect that.

**Comment by tomwayson** [comment]
To be more clear, I think the way to handle this is to specify the lowest supported version in package.json w/ a ^, like `"vega": "^2.0.1"`. The docs site can then use more recent versions like 2.5.2 (in part as a way to verify that it works on more recent releases). Then the README can indicate minimum supported version along w/ a statement about what versions it's been tested on since, like [we did in angular-esri-map](https://github.com/Esri/angular-esri-map#dependencies).

**Comment by tomwayson** [comment]
Resolved in #177
