### ISSUE TITLE
Use npmcdn for CDN links in docs

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#179]
``` html
  <script type="text/javascript" src="https://npmcdn.com/arcgis-cedar/dist/cedar.js"></script>
```

Will always point to latest release.

**Comment by Qberto** [comment]
Very helpful - Thanks!

**Comment by tomwayson** [comment]
Specifically, need to update the [Loading section of README](https://github.com/Esri/cedar/blob/8698df3e61142ec22b1e0aac1f627f095aafed20/README.md#loading-cedar). And then we need to make the changes prescribed in #171 to point the tutorial back there.

The docs pages themselves [run off local copies of cedar/vega/d3](https://github.com/Esri/cedar/blob/8698df3e61142ec22b1e0aac1f627f095aafed20/site/source/partials/header.hbs#L62-L64), and I don't think that should be changed to NPM CDN.

**Comment by jgravois** [comment]
just an fyi that its https://unpkg.com now.

if you want to do this, you should probably consider publishing the `charts/` directory to npm too so that folks don't see 404's when trying to reference stock types.
