### ISSUE TITLE
Query properties of the Cedar dataset doesn't works with all MapServices

### ISSUE THREAD

**Issue by Jimeno0** [Esri/cedar#186]
Hi there,

I'm testing the [Cedar library](https://esri.github.io/cedar) and I found out that the query properties of the dataset needed to group values doesn't works with services that it should works.

I have an example [here](http://jsbin.com/koborod/6/edit?html,output) with four couples of variables where you can check what Im saying. It works for the first and the second couple of variables but it doesn't for the third and the fourth couples.

I hope it helps to fix it (or to figured out how it works for beginners in Cedar like me). 
Anyway congrats for the work, It looks amazing! =)

**Comment by benstoltz** [comment]
@Jimeno0 Hey, the third and fourth pairs of variables actually do work. You had the output fields set to count_SUM, but apparently in sampleserver6 it should be count_sum instead. Data loads in fine once those are changed :)

**Comment by Jimeno0** [comment]
Yeah, It works!
I don't know why but it looks like the server always returns lowecase field names either I set the _outStatisticFieldName_ caps or lowercase.

Thanks so much Ben! I will keep it in mind for the next time =)

**Comment by benstoltz** [comment]
No problem! Glad it worked out. Keep in mind it might just be sample server 6 shenanigans.
