### ISSUE TITLE
Axes appearence question

### ISSUE THREAD

**Issue by Jimeno0** [Esri/cedar#187]
Hi guys,

Im having some troubles with the graphic axes and bars view. When there are much more elements in the X than the Y axe the graphic looks like no bars are being display and the axes looks tight. 

<img width="677" alt="cedaraxesissue" src="https://cloud.githubusercontent.com/assets/17181019/15120068/30ff1d96-1614-11e6-866b-b8fb74005e49.png">

I figured it out testing [this drill down](http://jsbin.com/vinilox/edit?html,output) If you click on most of the bars you will see what Im talking about. But if there aren't to much X elements to display like in  [this](http://jsbin.com/vukawi/edit?html,output) you can check that it works perfectly.

Thanks for you work =)

**Comment by benstoltz** [comment]
@Jimeno0 Looking into this further it seems that the overall height of the chart is not changing when the values change. So those super long value names take up the entire height of the chart object. If you end up giving the chart an initial height of say.....5000 then everything works (though things are grossly oversized). I'll look into how we are doing things and try to get this resolved.

**Comment by ajturner** [comment]
@jimeno0 as @benstoltz points out, Cedar is prioritizing displaying entire label over chart size. We could consider adding label truncation, but this gets very difficult to do automatically as it may cause labels to be non-readable or differentiable. 

Potential options:

- Option to limit x or y axis label lengths. Elide the middle or end when it is too long (e.g. `Wood, corten, steel, photographs on acrylic panels' -> `Wood, c..` or `Woo..els`) 
- Don't display axis labels and only rely on-hover/click interactions. Makes chart visible but difficult to read
- Put labels next to the bar (or other display). Likely would junk up the chart.

Have you seen other examples of usable charts with very long label names that you could share examples?

**Comment by Jimeno0** [comment]
Hi guys, 
I haven't found any other example yet.
I think that the option about to don't display axis labels could work for many cases but I can't figured out how to do it. Any clue?

Thanks in advance =)

**Comment by benstoltz** [comment]
@Jimeno0 sorry for taking so long. So figured out how to truncate label lengths.

In the bar spec file we'd want to add `"text": {"template": "{{ datum.data | truncate:20}}"}` to `axes` > the x axes > `'labels`

I'll try to get this updated shortly (tm).

**Comment by benstoltz** [comment]
@Jimeno0 In the most recent version of Cedar you can do...
```js
  //show the chart
  chart.show({
    elementId: "#chart",
    maxLabelLength: 20 // Or whatever number here
  });
```

And your axes labels will be truncated to that length.
