### ISSUE TITLE
Something wrong with cedar.js

### ISSUE THREAD

**Issue by Jimeno0** [Esri/cedar#201]
Hi guys,
Sorry to disturb you but I think something wrong is going on inside `cedar.js`.
No Cedar graphic can be displayed (Not even the samples from your [examples page](http://esri.github.io/cedar/examples/bar.html)). 

I found it on an app example about the [Crime in Washington](https://jimeno0.github.io/my-calcite/crime-dc-white-blue.html) that I create to test Calcite+Cedar and no graphic is been displayed. Just get the error: `Uncaught TypeError: chartCtor is not a function`.

Hope it helps =)

**Comment by benstoltz** [comment]
@Jimeno0 Thanks for the heads up, looking into it.

**Comment by benstoltz** [comment]
@Jimeno0 Sorry about that....apparently the proper version of Vega wasn't being pulled in. Fixed and the docs site && your application look like they are working properly now.

Thanks so much for the heads up!

**Comment by Jimeno0** [comment]
That was fast! 
Pleasure to help @benstoltz  =)
