### ISSUE TITLE
add example image in README

### ISSUE THREAD

**Issue by jgravois** [Esri/cedar#230]
just in case @laurenancona is [subtweeting us](https://twitter.com/laurenancona/status/788844630947328000)

**Comment by laurenancona** [comment]
No idea what you mean, @jgravois, I _never_ subtweet  ;)

**Comment by benstoltz** [comment]
👍 Will do.

**Comment by tomwayson** [comment]
This would be the output of the example code in the [Using Cedar](../#using-cedar) section of the README.

![image](https://cloud.githubusercontent.com/assets/662944/21374451/bf902fbe-c6db-11e6-8882-3fb25e91cce9.png)

It's not the snazziest chart, but it goes w/ the code. I also have a fiddle that goes w/ that https://jsfiddle.net/tomwayson/za4L3432/ that we can link to from the image and/or below the code.

@benstoltz if that works for you I can add this to #241

**Comment by jgravois** [comment]
don't ever change 😉
