### ISSUE TITLE
Error using "var series" in all examples

### ISSUE THREAD

**Issue by lfpvGitHub** [Esri/cedar#257]
I noticed all examples have been changed to add "series" into them.

I have created several charts using the following syntax (example for bar charts)

```
var dataset = {
        "url":"https://services.arcgis.com/bkrWlSKcjUDFDtgw/arcgis/rest/services/It's_a_Tornado_Map/FeatureServer/0",
        "query": {
          "groupByFieldsForStatistics": "state",
          "outStatistics": [{
            "statisticType": "sum", 
            "onStatisticField": "injuries", 
            "outStatisticFieldName": "injuries_SUM"
          }]
        },  
        "mappings":{
          "x": {"field":"state","label":"State"},
          "y": {"field":"injuries_SUM","label":"Injuries"}
        }
      };
        var chart = new Cedar({"type": "bar", "dataset": dataset});

      //show the chart
      chart.show({
        elementId: "#chart"
      });
````
However, when I used the new version of your example, see below:
```
`var chart2 = new Cedar({"type": "bar"});

  var datasets2 = [
    {
      "data": {
        "features":[{"attributes":{"Zip":20005,"Number_of_SUM":327}},{"attributes":{"Zip":20024,"Number_of_SUM":517}},{"attributes":{"Zip":20017,"Number_of_SUM":597}},{"attributes":{"Zip":20015,"Number_of_SUM":707}},{"attributes":{"Zip":20037,"Number_of_SUM":760}},{"attributes":{"Zip":20018,"Number_of_SUM":1052}},{"attributes":{"Zip":20012,"Number_of_SUM":1184}},{"attributes":{"Zip":20007,"Number_of_SUM":1584}},{"attributes":{"Zip":20008,"Number_of_SUM":1625}},{"attributes":{"Zip":20003,"Number_of_SUM":1869}},{"attributes":{"Zip":20009,"Number_of_SUM":1945}},{"attributes":{"Zip":20001,"Number_of_SUM":2164}},{"attributes":{"Zip":20010,"Number_of_SUM":2282}},{"attributes":{"Zip":20019,"Number_of_SUM":3278}},{"attributes":{"Zip":20011,"Number_of_SUM":3817}},{"attributes":{"Zip":20020,"Number_of_SUM":3901}},{"attributes":{"Zip":20032,"Number_of_SUM":4360}},{"attributes":{"Zip":20016,"Number_of_SUM":4681}},{"attributes":{"Zip":20002,"Number_of_SUM":5590}}]
      }
    }
  ];

  var series2 = [
    {
      "category": { "field": "Zip", "label": "Zip Code" },
      "value": { "field":"Number_of_SUM","label":"Total Students" }
    }
  ];

  chart2.tooltip = {
    "title": "{Zip}",
    "content": "{Number_of_SUM} Students in {Zip}"
  }

  //assign to the chart
  chart2.datasets = datasets2;
  chart2.series = series2;

  //show the chart
  chart2.show({
    elementId: "#chart-data",
    renderer: "svg"
  `});
```
I get the following error: " Uncaught TypeError: Cannot read property 'x' of undefined " which comes from line 199 of VM331 cedar.js.

I am not sure what the issue is, so I thought I will highlighted here.

I tried changing the series2 "category" and "value" to "x" and "y" but this does not solve the issue. This is the case for all examples. I am currently trying to use the grouped chart type and I can't get this to work.

I have also tried the examples within my HTML and JSFiddle and the error is still the same.

Thank you.

**Comment by benstoltz** [comment]
Hey there @lfpvGitHub, sorry for the slow response. Do you have a link to that jsfiddle? Also double checking you are currently using the most recent version of Cedar right?

**Comment by lfpvGitHub** [comment]
Hi @benstoltz many thanks for getting back to me. Yes, I am using what I believe is the latest version of Cedar. 
I tried adding my code to jsfiddle and it was just not happening. I do apologize before hand for doing this but I have attached my code below.

`<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no"/>
    <title>Simple Map</title>
    <link rel="stylesheet" href="https://js.arcgis.com/3.19/esri/css/esri.css">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.4/foundation.min.css">

    <style>
      * {
      box-sizing: border-box;
      } 
      html, body, #map {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
    
    <script>
      window.dojoConfig = {
        async: true,
        packages: [
          {
            name: 'd3',
            location: 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6',
            main: 'd3.min'
          }, {
            name: 'vega',
            location: 'https://cdnjs.cloudflare.com/ajax/libs/vega/2.6.1',
            main: 'vega.min'
          }, {
            name: 'cedar',
            location: 'https://unpkg.com/arcgis-cedar@0.7.0/dist',
            main: 'cedar.min'
          }
        ]
      };
    </script>
    <script src="https://js.arcgis.com/3.19/"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script>
      //load the visualization api
      google.load("visualization", "1", {packages:["corechart"]});

      require(["cedar", "esri/map", "esri/layers/FeatureLayer", "esri/symbols/SimpleMarkerSymbol", "esri/symbols/SimpleLineSymbol","esri/renderers/SimpleRenderer",  "esri/renderers/UniqueValueRenderer", "esri/Color", "esri/toolbars/draw", "esri/symbols/SimpleFillSymbol", "esri/layers/GraphicsLayer", "esri/graphic", "dojo/domReady!"], 

      function(Cedar, Map, FeatureLayer, SimpleMarkerSymbol, SimpleLineSymbol, SimpleRenderer, UniqueValueRenderer, Color, Draw, FillSymbol, GraphicsLayer, Graphic) { 


      var defaultSymbol = new SimpleMarkerSymbol(SimpleMarkerSymbol.STYLE_CIRCLE, 9,
        new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,
        new Color([198,12,70,1]), 1),
        new Color([248,187,37,0.9]));

      var rend = new SimpleRenderer(defaultSymbol);

      var featureLayer = new FeatureLayer("https://services6.arcgis.com/UsYsRnGSuO0r8uif/arcgis/rest/services/FWW/FeatureServer/0",{
        mode: FeatureLayer.SNAPSHOT,
        outFields: ["*"]
      });

      //create esri map
      var map = new Map("map", {
        center: [-99, 38.9],
        zoom: 4,
        basemap: "topo",
        smartNavigation: false
      });

      map.on('load', function() {
        map.disableScrollWheelZoom();
      });


      window.map = map;

      featureLayer.setRenderer(rend);
      map.addLayer(featureLayer);


      var chart = new Cedar({
        "type": "grouped",
        "tooltip": {
          "title": "{Y_M}",
          "content": "{nitrate} NO3"
        },
        "datasets":[
          {
            "url": "https://services6.arcgis.com/UsYsRnGSuO0r8uif/arcgis/rest/services/Flinks/FeatureServer/0"
          }
        ],
        "series": [
          {
            "category": { "field": "Y_M", "label": "time" },
            "value": { "field":"nitrate","label":"NO3" }
          },
          {
            "category": { "field": "Y_M", "label": "time" },
            "value": { "field":"phosphate","label":"PO4" }
          },
        ]
      });

        chart.show({
          elementId: "#chart",
          autolabels: true
        });

    });
    </script>
  </head>

  <body>
 
    <div id="map" style= "width: 100%; height: 50%; float: left; border:1px solid black;"></div>
    <div id="chart"> </div>
    

  </body>
</html>
 `

I hope this will help solving the issue. Regards.

**Comment by benstoltz** [comment]
Hey @lfpvGitHub, looks like you're pointing at Cedar version 0.7.0. Try updating that to 0.9.1

Totally my fault, need to update the main Readme to point to the proper version.

**Comment by lfpvGitHub** [comment]
Hi @benstoltz that just did the trick. Many thanks for the help!
