### ISSUE TITLE
amCharts vs plot.ly

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#266]
We've hit some growing pains w/ our current vega architecture. In particular it is challenging to create vega specfications that:
- accept an arbitrary number of series
- look "nice"

The next version (1.0) of cedar is likely to be based on amCharts, but before we took the plunge, we thought we it would be remiss not to seriously consider [plotly.js](https://plot.ly/javascript/) since it is very popular. Plot.ly was also the front runner (after "Show me the results") in this [twitter survey](https://twitter.com/tomwayson/status/866704141447331840).

Below are the findings of our (far from comprehensive) research. We're posting these here for further input from the Cedar community as a place to carry on the conversation from the above survey (who's sample size is far too small to be all that meaningful).

It should be noted that we _hope_ to one day enable users to be able to choose from multiple "engines" (i.e. use cedar with either cedar-amcharts, cedar-plotly, cedar-vega, etc), but that's not on the immediate roadmap.

## Chart Types

TODO: seems like they are on par here, but as always, the devil's in the details.

## Chart Events

TODO:

## Chart Features

TODO: Regions, zoom, save as, download, etc. Again, they seem on par, but devil's in the details.

## Data

Each library handles data quite differently.

amCharts:
amCharts expects the data to be an array of objects, each analogous to rows in a table. This is a similar format to the array of features returned in featureSets, _but_ we still have to preprocess those to strip `attributes`.

plotly:
plotly expects the data to be an array of arrays of scalar values (called traces - each is a series to be plotted). This means that any feature set data will need to be transformed from what is effectively an array of rows (features) to arrays of columns. However, it does make it easier to plot series that come from different data sources (queries, etc) b/c they don't have to be joined together. Plotly exposes an API to [write a plugin](https://github.com/plotly/plotly.js/pull/499), which we _could_ use to create a generic "features to traces", which might be useful to people, but I suspect it would be more efficient for Cedar to have custom logic about how it preprocess the data before handing off to plotly.

**Winner: tie**
amCharts' row-like style is familiar, and might give amCharts the edge if we didn't have to preprocess features to strip `attributes`. Plotly should be easier to with data that comes from multiple sources.

## Architecture

amCharts:
amCharts is a standalone library w/ no dependencies.

plotly:
plotly is based on D3 (for SVG charts) or [stack.gl](http://stack.gl/) for Web GL charts. plotly.js is the web implementation of the plotly ecosystem.

**Winner: plotly**
Plotly has the advantage of being based on popular open source libraries, and it is modular, though the way they currently package and ship the library doesn't allow Cedar or our users to take full advantage of that composition and modularity (see the File Size section below). Still, in the long run, the fact that plotly maintainers can focus on implementing their high level abstraction (the "plotly API"), and letting D3 or stack.gl worry about the low level problems gives plotly the edge here (I think).

## License and Community

amCharts:
amCharts is free w/ a small watermark on the chart. Licensed users (including Esri apps) can use a copy of the library that doesn't include the watermark. Because Esri has a license, we get support.

plotly:
plotly.js is open source, so there is an active developer community.

**Winner: plotly**
Even though amChart's license is very reasonable, any non open source license will raise questions and doubt for Cedar developers. As far as community, plotly's 6k+ github stars vs amCharts' ~211 says it all.

Tom's opinion (based on minimal use of each library): It _seems_ like license fees in amCharts are paying for better docs rather than faster development of features at this point. I'm not sure if plotly's active and developer community translates to fast development of features, or if too many voices are causing stagnation (like C3), but I'm more confident that plotly will be around and evolving in the long run.

## Documentation

[amCharts](https://www.amcharts.com/javascript-charts/) includes a [complete API reference](https://www.amcharts.com/knowledge-base/) and an [interactive chart builder](https://live.amcharts.com/).

Plot.ly only documents new features by adding examples rather than API reference. Like amCharts, plotly does have an [interactive builder](https://plot.ly/create/).

**Winner: amCharts**
amCharts has a only a _slight_ edge here.

## File Size

_all sizes below are minified+gzip_

amCharts:
* min (just bar/line): ~75kB
* all chart types: ~84kB
* full (includes download/save tools): ~725kB

![image](https://cloud.githubusercontent.com/assets/662944/26316295/a5318c70-3ec8-11e7-8400-f30d4ecfa2fc.png)

plotly (as far as I can tell these bundles _do include_ d3):
* [basic](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-basic) (scatter, bar, pie, line): 212.1 kB
* [cartisian](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-cartesian) (all chart types): 234.7 kB
* [full](https://github.com/plotly/plotly.js/blob/master/dist/README.md#bundle-information): 655.3 kB

It is possible to [create your own plotly bundle](https://github.com/plotly/plotly.js#modules) that _in theory_ would include just what is needed by Cedar, but then we'd have to know ahead of time what our users would use.

I think for amCharts we have to assume [we'll have to use their pre-built bundles for the foreseeable future](https://github.com/amcharts/amcharts3/issues/42#issuecomment-222605396).

**Winner: amCharts**
Plotly's full build is smaller than amCharts and includes more (like webgl 2D and 3D), but I would not want to impose that on users that aren't going to use those features. Whereas w/ amCharts we can easily ship just the functionality that is needed, and users can opt in to remaining functionality (download, etc) as needed. The only way plotly would be better would be if we were able to create a custom build with all the chart types (and nothing extra) that is smaller than the amCharts series+xy+radar files, but even then, unlike amCharts, you would not be able to dynamically load remaining functionality at runtime.

## Appearance and Theming
The better the out of the box styles, the less work we have to do in custom specifications. Support for themes makes this easier. I also assume we'll ultimately want to ship a default (calcite) theme and allow users to create their own custom themes to match their brand.

amCharts
This is subjective, but I (Tom) think amCharts have a more refined appearance out of the box, though I do think there is way too much bouncy animation.

I can't find documentation on how to create a custom theme, but [they are pretty simple](http://extra.amcharts.com/tutorials/themes/amcharts/themes/light.js) and it's easy to see how you could create your own.

ploltly
I think the default appearance of plotly's D3 charts are better than vega or C3, and just like those other libraries, with some work can be made to look very nice. However, out of all those libraries and amCharts, Plotly is [the least CSS friendly](https://github.com/plotly/plotly.js/issues/1195#issuecomment-262793638), so all changes have to be made using JSON.

What makes this even worse is that Plotly says they have [built-in themes](https://help.plot.ly/themes/), but I can't see how to use them (maybe outdated docs?).

**Winner: amCharts**

**Comment by driskull** [comment]
Nice writeup @tomwayson! I agree with pretty much all of that. For me the big points were Architecture, license and community. WebGL and open source earn points.

amCharts would be fine too, but we'll have to have a watermark

**Comment by tomwayson** [comment]
forgot to close this after decided on amCharts long ago
