### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by dmfenton** [Esri/cedar#268]
http://esri.github.io/cedar/examples/map.html

The map never loads

**Comment by jgravois** [comment]
the only failed web request i see when i load that page is to:
```
https://opendata.dc.gov/datasets/4919ca2fa0894de18e4752a5e16ca683_22.geojson
```

**Comment by dmfenton** [comment]
That domain does not support https




On Thu, Jul 6, 2017 at 5:25 PM -0400, "john gravois" <notifications@github.com<mailto:notifications@github.com>> wrote:


the only failed web request i see when i load that page is to:

https://urldefense.proofpoint.com/v2/url?u=https-3A__opendata.dc.gov_datasets_4919ca2fa0894de18e4752a5e16ca683-5F22.geojson&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=m46900hNBbRbuDjczmHaUO51NO7Zjmm8qVz5v1hju2laq5MXvX18l40QhOOQJ-l3sVBOup-5xll393ID_SfO_sISWQBBGtO3VyDGGCjKnKGSjAkdbZIxh5lfmJ2LRy47y7FbTlbDDdytLB2IO3lZ8Q&m=pzOT1AGiIg0ON4NQG91OAQqPS9BJX0GF8Ii79OgAI8I&s=W5NPdMWDlnCcr8hikc3N5OqY-XD085mzvMRTRFZ-okw&e=

**Comment by jgravois** [comment]
deployed.

teamwork makes the dream work. (second time i've said that [today](https://twitter.com/geogangster/status/883038468053417984))

**Comment by dmfenton** [comment]
Found another http://esri.github.io/cedar/examples/spec-url.html
