### ISSUE TITLE
v1 API design questions

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#278]
- do we need to relate series to datasets (i.e `datasets[i].id` and `series[j].datasteId`)?
 - how should datasets indicate that they should be joined or appended ("merged") - `merged: true` vs. `join: 'join_field_name'`
 - `override` vs `overrides` (we use the former in v0, the latter in v1, why?)
 - what should be the API for passing inlined data?
 - what should be the API for transforming data?

**Comment by tomwayson** [comment]
re: realting series to datasets, see #277

**Comment by tomwayson** [comment]
re: api for passing inlined data

@ajturner suggested "should allow passing in an array of data objects."

I suggest supporting a single, top level `data` property as an alternative to `datasets`. This would be an array of objects (not features, so each would **not** have `attributes`). The reason for having a single `data` object as opposed to an array of `data` objects is that if the user is already cooking their own data, they don't need us to help join or append ("merge") them.

That said, I also think that each dataset should support a `featureSet` property as an alternative to `query` that would [work the way the v0 `dataset.data` property did](https://esri.github.io/cedar/examples/inlined-data.html). This way you could mix and match dynamically queried records w/ static inlined ones.

**Comment by tomwayson** [comment]
re: transforms, see #285

**Comment by ajturner** [comment]
Re `data` we should keep static data, services, featureSets, GeoJSON from GitHub, etc all at the same level. 

This is a simpler API, as there aren't "special cases", just one case with a subclass variation.

Second, I would like to join a static dataset with a feature service. For example,  I have school rating from a third-party API as a static dataset and I want to Chart Rating vs. Student/Teacher ratio. If we keep the static array as a dataset then everything is the same as if that rating came from a feature service.

**Comment by tomwayson** [comment]
> we should keep static data, services, featureSets, GeoJSON from GitHub, etc all at the same level.

So no top level `data`? In that scenario, if you were cooking your own array of objects, you'd have to do: 

```
{
  type: 'bar',
  datasets: [{ data: myObjArr }],
  series: {...}
}
```

I could live w/ that, but I still prefer:

```
{
  type: 'bar',
  data: myObjArr,
  series: {...}
}
```

> If we keep the static array as a dataset then everything is the same as if that rating came from a feature service.

Unless I misunderstand, that is exactly what I propose above with `datasets[i].featureSet`. So in this example the static features will get joined w/ the query results:

```
// in this case the features are coming from a layer on a map
// but they could be the response to some previous query
// or just built by hand
var myFeatureSet = {
  features: graphicsLayer.features
};
{
  type: 'bar',
  datasets: [{
    featureSet: myFeatureSet
  }, {
    url: '...'
    query: {...}
  }],
  series: {...}
}
```

I think what you want is pretty much the same thing, only using `data` instead of `featureSet` as the key. I was thinking of using `featureSet` b/c it's explicit about what it contains and I expect `data` to be an array of non-feature (i.e. no `attributes`) objects. 

That said, `featureSet` would be a breaking change from the "interim" (transitional) JSON format that we set up, and therefore existing OpenData/Hub pages that use it could break. Knowing you, I suspect you also prefer `data` because it's more terse :wink:, and also figure that we could be smart about how we handle it, like:

```
if (dataset.data instanceof Array) {
  // treat it as an array of non-feature objects
} else if (dataset.data.features && dataset.data.features instanceof Array) {
  // data is a feature set, handle accordingly
}
```

I can live w/ that.

So, anyone opposed to `datasets[i].data` for all static data passed in?

**Comment by ajturner** [comment]
I like
```
{
  type: 'bar',
  datasets: [{ data: myObjArr }],
  series: {...}
}
```

Because it is consistent (and terse). We can always support the non-nested later, right?

**Comment by tomwayson** [comment]
Sounds good. I'll open a PR for that.

**Comment by tomwayson** [comment]
With #332, all the individual questions above are now being tracked in their own issues, so closing this.
