### ISSUE TITLE
v1.x JSAPI map example

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#334]
Base on this https://esri.github.io/cedar/examples/filter-chart-by-map-extent.html

**Comment by tomwayson** [comment]
Maybe a first pass at this could be just a JS Bin/Fiddle like #339

**Comment by tomwayson** [comment]
if not a fiddle, then this depends on #337

**Comment by jPurush** [comment]
https://codepen.io/jPurush/pen/JpzXoz

**Comment by tomwayson** [comment]
resolved in fe6a99ef32fe5a6463540bf088af4a431df52015
