### ISSUE TITLE
Definition supports legend

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#389]
I suggest we base this mostly on the pro spec:

```json
    "ChartLegend": {
        "type": "type: string; const-value: chartLegend",
        "visible": "type: boolean; description: true",
        "title": "type: string",
        "alignment": "type: string; domain: <left | right | top | bottom>",
        "valueFormat": "type: string"
    },
```

I say we start by supporting the ones that line up  [AmCharts legend properties](https://docs.amcharts.com/3/javascriptcharts/AmLegend):

| Pro  | AmCharts |  Notes  |
| ------------- | ------------- |  ------------- |
| `visible`  | `enabled`  |    |
| `title`  | `labelText`  | AmCharts also has `accessibleLabel`, should we set that? |
| `alignment`  | `position`  |  in addition to the above values, AmCharts supports `absolute`, but we won't deal w/ that here, consumers will have to use `overrides` if they need that  |

A future iteration can support Pro's `valueFormat` by supplying AmCharts with a `valueFunction`, but I think we should be considering text formatting more broadly at that time.

For #375 the barest minimum that we need to support is `legend: { visible: true }`, but if `title` and `alignment` are easy to add, I'm not opposed to including those in the initial PR.

**Comment by tomwayson** [comment]
cc @phlorah @ajturner

**Comment by benstoltz** [comment]
Right now we have
```
export interface ILegend {
  enable?: boolean
}
```

Should be painless to switch that over to be `visible` and the other two parameters.
