### ISSUE TITLE
Multi-series charts mis-chart values when attribute missing from query response

### ISSUE THREAD

**Issue by benstoltz** [Esri/cedar#406]
When visiting http://cedar-v1.surge.sh/ > bar-grouped. The chart displayed does not accurately display the data as returned from the service response. Dewitt and Fayetteville values should be switched. Dewitt’s service response is only Elementary Schools with no values for High School and Middle School. This is causing some issues as it throws off what’s displayed.

**Comment by tomwayson** [comment]
critical, wow

**Comment by benstoltz** [comment]
Cranky Tom is cranky.
