### ISSUE TITLE
how to set up cedar properly to chart object arrays?

### ISSUE THREAD

**Issue by deschatt** [Esri/cedar#465]
hi, I'm accessing data from a text file upon loading and putting the necessary data into object arrays, then want to generate line charts from it.   I would like two separate lines so I have two separate "value" specifications.  I was told object arrays are the proper way to do all of this.  I verified the object arrays are being populated properly with that data, just need to figure out how to chart it and display it.  

I'm getting an error that one of the object array variables, timeTable, isn't defined.  I don't know if I'm not referencing the cedar libraries properly with my references on top, or if the problem is the syntax of my cedar data definitions.  There was no example explicitly for line charts, so I also don't know if I have that proper syntax and references that I need for that.  Thanks for any help!

	<script src="https://www.amcharts.com/lib/3/amcharts.js"></script> 
	<script src="https://www.amcharts.com/lib/3/serial.js"></script>
	<script src="https://unpkg.com/@esri/arcgis-rest-request"></script>
    <script src="https://unpkg.com/@esri/arcgis-rest-feature-service"></script>
    <script `src="https://unpkg.com/@esri/cedar/dist/umd/cedar.js"></script>

    map.on("click", createChart);

    function createChart(event) {
             -      
             -
             -
               var table = [];
               var addObject = {};

               //////////////////////////////////////////////////////////////////////////////////////////////////
               // Read in time values, water elevation values, and surface elevation constant to object array
               // of {timeTable, waterElevationTable, landElevationTable}
               //////////////////////////////////////////////////////////////////////////////////////////////////
               function populateObjectArray() {
			  for (let j = 0; j < 37; j++) {
                             addObject = {timeTable: time[j], 
                                         waterElevationTable: waterElevation[j], 
                                         landElevationTable: landElevation};
                             table.push(addObject); 
                      }
	           }

               var datasets = [{
                  "data": "table",
                  "name": "water elevation series"
               }];

               var series = [{
                  "category": {"field": timeTable, "label": "Time (hours)"},
                  "value": {"field": "waterElevationTable", "label": "Water elevation (feet)"},
                  "value": {"field": "landElevationTable"},
                  "source": "water elevation series"
               }];

               var elementId = 'chart';
               var chart = new cedar.Chart(elementId, {"type": "line"})
                  .datasets(datasets)
                  .series(series);

               //need to set up Popup above and link to map's infoWindow property
               map.infoWindow.setTitle("Time vs. Water elevation");
               map.infoWindow.setContent(chart.show());
               map.infoWindow.show(event.mapPoint, map.getInfoWindowAnchor(event.screenPoint));

            }

**Comment by tomwayson** [comment]
I think you need `"data": table` instead of `"data": "table'"`

**Comment by deschatt** [comment]
works now, thanks Tom!
