### ISSUE TITLE
Allow passing request options to query

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#482]
I've recently encountered the need to override the [request options](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/) sent to `queryFeatures()`, specifically to force using `POST` instead of `GET` due to the server's limit on query string length. The problem is that [`queryDatasets()`](https://github.com/Esri/cedar/blob/fa484de376354e52e0af3ca552ec1ed94948b1c4/packages/cedar/src/query/query.ts#L12) does not currently allow that.

We could do this in a couple ways. We could either add a `requestOptions` property to [`IDataset`](https://esri.github.io/cedar/api/interfaces/idataset.html), or we could have `queryDatasets()` take an optional second argument like `requestOptions?: IRequestOptions`) which could be passed in from [`chart.query()`](https://github.com/Esri/cedar/blob/fa484de376354e52e0af3ca552ec1ed94948b1c4/packages/cedar/src/Chart.ts#L263) as something like `queryDatasets(this.datasets(), this.requestOptions()`. We could also ultimately do both of those and have the dataset's options override those of the chart.

I suggest starting by adding the property to `IDataset` since that is the most granular and offers the most bang for the buck.

**Comment by benstoltz** [comment]
I think adding it to `IDataset` first is a good idea. We can then subsequently add it as a optional second argument afterwards if we want.
