### ISSUE TITLE
Provide a way to get the actual count (instead of a sum) of a group by query

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#61]
When I specify a dataset like this:
```
  var dataset = {
    "url":"http://sampleserver5.arcgisonline.com/ArcGIS/rest/services/LocalGovernment/CitizenRequests/FeatureServer/0",
    "mappings":{
      "group": {"field":"severity","label":"Severity"},
      "count": {"field":"OBJECTID","label":"Count"}
    }
  };
```

I'm expecting it to send a query w/ the following outStatistics to the service:
```
[{"statisticType":"count","onStatisticField":"OBJECTID","outStatisticFieldName":"OBJECTID_COUNT"}]
```

Instead it sends:
```
[{"statisticType":"sum","onStatisticField":"OBJECTID","outStatisticFieldName":"OBJECTID_SUM"}]
```

Which is what I would expect if I set `mappings.sum` instead of `mappings.count`.

Am I missing something? Is there another way to group by and get counts instead of sums for another field?

**Comment by abakirov** [comment]
+1
It would be nice if mappings like these returned simple counts rather than sums:
```
"mappings": {
  "group": {"field":"severity","label":"Severity"}
}
```
... or something analogous
