### ISSUE TITLE
CDN Deployment

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#64]
Looks like the only way to load Cedar right now is by copying it locally to my HTTP server

**Comment by jgravois** [comment]
correct.  see #62 for more info.

**Comment by ajturner** [comment]
waiting for @jwieringa on a CDN domain and @dbouwman to push

Agreed we would like this for DevSummit next week.

**Comment by abakirov** [comment]
Could you please post the correct CDN URL here, if it's already available? (I'm currently using the source code and I was wondering if it's time to switch to CDN)

**Comment by jwieringa** [comment]
Hi @abakirov, I apologize for the delay. I'm waiting on a DNS record to be provided. I will follow up on the issue. At this time, I am not aware of a different CDN link to this code.

cc @ajturner @dbouwman

**Comment by ajturner** [comment]
we can also use https://cdnjs.com/

**Comment by benstoltz** [comment]
Closing. Now that we have deployed to NPM we can use: https://npmcdn.com/arcgis-cedar/dist/cedar.js which will stay up to date with the most recent version of Cedar. Docs and samples will be updated shortly. As well Cedar can be included into a project via bower and npm.
