### ISSUE TITLE
Labels should not overlap

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#65]
Reproducible with this feature service:
http://services.arcgis.com/pmcEyn9tLWCoX7Dm/arcgis/rest/services/CA_Hospitals/FeatureServer/0

And these mappings:
```
{
  "group": {
    "field": "Hospital_Ownership"
  },
  "count": {
    "field": "Number_of_Patients"
  }
}
```
![image](https://cloud.githubusercontent.com/assets/5304673/6382010/379ff91e-bcfa-11e4-82bd-69d3bce98ff4.png)

**Comment by abakirov** [comment]
I think this is how long labels should behave (word-wrap when needed, then eventually automatically rotate):
http://jsfiddle.net/nmsxtx02/1/

**Comment by benheb** [comment]
@abakirov super nice in theory, but so many use cases where this won't work, like when there's too many bins, or the chart is narrower. In trying to avoid adding logic to cedar to determine when to rotate labels, we've shifted to defaulting to a rotated label, and if users/devs want to override that option based on their app, they can. 

Here's an example, using the dataset you are using above: http://esri.github.io/cedar/examples/style-overrides.html

**Comment by abakirov** [comment]
Well, this is not a theory, this is real charting library (pretty good one!). If chart becomes narrower, every other label disappears and becomes available only as tooltips.

Looping in @arthaddad and @HeikoH for input/thoughts.

In our case data comes from user and it is our responsibility to take care of label placement. I don't like the fact that we will have to implement our own logic to decide when and how to word-wrap or rotate labels.

Speaking of word wrapping... SVG/Canvas does not even support automatic word wrapping. This has to happen on d3 level as indicated in this example:
http://bl.ocks.org/mbostock/7555321

**Comment by benheb** [comment]
Yep, well aware of high charts, and use it all the time. Fact is there's a lot of charting libraries out there that are great and have already resolved a lot of these issues. 

This seems like more of a philosophical question on what we want Cedar to be, and if we want it to be High Charts, why aren't we just using High Charts? To me the power of Cedar has always been the template, which allows you to pretty much make any type of chart with any definition you could possibly one. The other power of Cedar is the ability to supply a feature service URL get get a chart in return, without any of the logic needed there. As soon as Cedar starts trying to address all the use cases, it gets more complicated. So I've tried to address it as -- Cedar needs good defaults, but let's minimize the logic side. 

Now, maybe this isn't the best approach, and we need to continue to add more logic to Cedar-core (pull requests accepted!), but if that's the case I think we need to make a conscious decision to do so, and make sure what Cedar/Vega is, makes sense. 

I'm sure @dbouwman and @ajturner have thoughts here.

**Comment by abakirov** [comment]
I think the idea of template-based charts that automatically connect to feature services is very good. And the idea of company-wide defaults for charts also makes total sense.

Just want to propose maybe consider evaluating other charting libraries, not Vega, to use as rendering engine. Obviously, there are good commercial libraries out there but maybe there is also a free open source library that already handles sizing and labels positioning correctly (or at least better than Vega does it).

**Comment by ajturner** [comment]
Let's work with the Vega team to improve the engine.

Clearly automatic label layout is not a difficult capability - it just needs to be slightly abstracted, perhaps as a Vega JSON parameter and the implemented in that engine.

In fact, first would be testing the latest version and the v2 branch of Vega. If not, then let's submit an issue in their repo and work on a PR together.

There are many reasons for Vega in particular - including headless rendering, compatibility with R, Python ports and the very advanced scene graph generation that abstracts rendering from layout logic - portable to WebGL and Native runtimes

**Comment by abakirov** [comment]
More screen captures of the issue:

![image](https://cloud.githubusercontent.com/assets/5304673/7942655/7129d7ca-0914-11e5-9757-8402614804e3.png)

![image](https://cloud.githubusercontent.com/assets/5304673/7942669/849bbc74-0914-11e5-875e-019b57a0e2ac.png)

![image](https://cloud.githubusercontent.com/assets/5304673/7942699/b4a60500-0914-11e5-82f3-f7f622ce6540.png)

**Comment by ajturner** [comment]
![screenshot_6_4_15__2_50_pm](https://cloud.githubusercontent.com/assets/1218/7991840/21fba7a8-0ac9-11e5-9faf-a235a4fb07c2.png)

**Comment by ajturner** [comment]
@tomwayson I'm working on this issue now - to do the label placement & orientation I'll need to calculate statistics on the tick labels.

So I want to capture this data - seems like in [Cedar.update](https://github.com/Esri/cedar/blob/master/src/cedar.js#L326-L340) that the data are not being retained. 

Do you see any issues with keeping the data in an object? Could be a bit of memory, but flush it on updates.

**Comment by abakirov** [comment]
Renamed the issue... it is not enough to only resolve this for bar chart and specific dataset by rotating labels. There needs to be a generic solution so that labels never overlap, regardless of chart type, chart size, and data set. This is key, fundamental requirement for a charting library.

**Comment by ajturner** [comment]
thanks for the input @abakirov - we'll continue to investigate this and develop heuristics for label placement and truncation

**Comment by ajturner** [comment]
assigning to @phlorah and @ddred11 to document the heuristics for label logic. 

decisions need to be made on "too scrunched" "label orientiation" "truncation" "hiding labels", etc.

**Comment by dbouwman** [comment]
I'd also throw in that we need some input around how long

**Comment by abakirov** [comment]
@phlorah @ddred11 
Just wanted to re-iterate on my earlier proposal to just do what this other charting library does:
http://jsfiddle.net/nmsxtx02/1/

Note how nicely they handle labels.

You can resize output pane to see how labels respond:
![image](https://cloud.githubusercontent.com/assets/5304673/8751126/17f5cb04-2c60-11e5-8f86-70e0cf791992.png)

**Comment by arthaddad** [comment]
@phlorah

**Comment by ajturner** [comment]
just capturing examples of Highchart logic for @ddred11 design @phlorah heuristics

Narrow:
![edit_fiddle_-_jsfiddle](https://cloud.githubusercontent.com/assets/1218/8752851/1185b6ba-2c85-11e5-80b5-1926eaa6043a.png)

medium: 
![edit_fiddle_-_jsfiddle](https://cloud.githubusercontent.com/assets/1218/8752862/2d905ff4-2c85-11e5-9831-7004d3e3f3fd.png)

wide
![edit_fiddle_-_jsfiddle](https://cloud.githubusercontent.com/assets/1218/8752873/3bbcd24c-2c85-11e5-930c-89aba325347a.png)

cedar
![bar_chart___esri_cedar](https://cloud.githubusercontent.com/assets/1218/8752933/96b9b5ac-2c85-11e5-981b-7ad8f5aa4a36.png)

- differences: high-chart rotates Counter-clockwise; cedar rotates clockwise. 
 - CCW takes advantage of Y-axis spacing
- high-charts does string truncation. Cedar does not automatically

**Comment by ajturner** [comment]
closing this large issue - we can open specific ones as they come up (and I know there are a few)
