### ISSUE TITLE
Sizing Issues on chart frame

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#66]
There seems to be another open issue related to sizing/responsiveness but this one slightly different.

I took this [default basic scatter.json](http://esridc.github.io/cedar/data/templates/scatter.json) and changed width/height to the values I needed (555px by 555px in this case). The chart got renderer in 809 x 615 box:
![image](https://cloud.githubusercontent.com/assets/5304673/6382430/53bed612-bcfd-11e4-98ce-e9741acdbc1d.png)

This issue is not specific to scatter plot, it is also reproducible for bar chart (the size discrepancy for bar chart is much less notable).

Please use this feature server to repro:
http://services.arcgis.com/pmcEyn9tLWCoX7Dm/arcgis/rest/services/CA_Hospitals/FeatureServer/0
... and use `Mortality_Readm_Rate` as X and `Number_of_Patients` as Y.

**Comment by benheb** [comment]
@abakirov resizing appears to be working for me, any chance you're overriding the width/height in the chart initialization? Is there a link to this demo I could look at?

**Comment by abakirov** [comment]
An example is here:
http://esridc.github.io/cedar/examples/scatter-def-url.html

If you open spec JSON you will notice specific width and height:
![image](https://cloud.githubusercontent.com/assets/5304673/6513910/706f2cd0-c333-11e4-834b-a12138ad4e00.png)

But if you go Dev tools will notice that rendered size is quite different:
![image](https://cloud.githubusercontent.com/assets/5304673/6513937/acc904ee-c333-11e4-936a-8c34c0542e67.png)

There must be something I'm missing here... does it ignore the width/height in the template sizes to container?

**Comment by abakirov** [comment]
It looks like template size applies to plot area, not the whole chart:
![image](https://cloud.githubusercontent.com/assets/5304673/6514159/20760738-c335-11e4-8a5a-8f4522b8e8e8.png)

I would expect the whole chart to have the defined size.

**Comment by benheb** [comment]
@abakirov yep, that is a bit strange. Any chance you can work with that though? As long as resizing works, should be able to account for the labeling, and make the chart a bit smaller? I'll continue to look.

**Comment by abakirov** [comment]
Well, ideally I'd like to have either automatically resize to container size or, alternatively, I should be able to specify outer chart size (because I want to fit into given area on the screen; the size of this area depends on the app, I don't have freedom here).

**Comment by benheb** [comment]
Yep, it's pretty clear vega is sizing based off the assumption no ticks/labels/titles, also prior to any padding you'll add. Looking at vega right now so see if there's a nice way override. Maybe @dbouwman or @ajturner have an idea off the bat.

**Comment by ajturner** [comment]
I suggest bringing this up in the Vega github repo directly. Maybe Vega 2 can add that or we could submit a PR there.

**Comment by abakirov** [comment]
@ajturner 
Do you have any idea when/if this will be fixed?

Understood that this is very difficult to fix. I wonder if this is even possible to fix with Vega... it may require a completely different rendering strategy to address this type of low-level issue (along with [overlapping labels](https://github.com/Esri/cedar/issues/65)). I'd say one needs to render labels first and than allocate remaining space to plot area. Or even rendering should happen in several render-measure-render cycle... or something along those lines.

What's your take on this?

**Comment by abakirov** [comment]
Just want to emphasize the severity of this issue once again... incorrect sizing strategy won't let us layout the chart correctly:

![image](https://cloud.githubusercontent.com/assets/5304673/7942736/08e4609e-0915-11e5-9e1f-650a497c0275.png)

... labels overflow and we cannot center-align the chart because the outer rendered chart size is basically random.

Data source:
http://services.arcgis.com/qvVnajWeXlTaQQu1/ArcGIS/rest/services/sf_stores/FeatureServer/0

**Comment by ajturner** [comment]
@abakirov this is fixed with the merged PR's. please verify and re-open if you still see an issue.
