### ISSUE TITLE
http://esridc.github.io/cedar is down

### ISSUE THREAD

**Issue by HeikoH** [Esri/cedar#75]
@ajturner 
![image](https://cloud.githubusercontent.com/assets/2171931/6602253/b088f9a6-c7d7-11e4-8b5c-d7b8a9f4238c.png)

**Comment by ajturner** [comment]
It moved to http://esri.github.com/cedar

**Comment by ajturner** [comment]
I will add a redirect

**Comment by HeikoH** [comment]
...maybe update this link:
![image](https://cloud.githubusercontent.com/assets/2171931/6602489/31706008-c7d9-11e4-8c9d-319a17322792.png)

**Comment by ajturner** [comment]
It is (now) :)
