### ISSUE TITLE
Suggestions for responsive charts

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#89]
The responsive example is a good starting point, but it would be great if the Cedar API provided an option to indicate that the chart is responsive, and handled that so that the client code does not have to. I like the way that Chart.js does this with these two chart options:

```js
    // Boolean - whether or not the chart should be responsive and resize when the browser does.
    responsive: false,

    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio: true,
```

If responsive is true, Chart.js will add a debounced handler for window resize that updates the chart height / width based on the new size of the chart's dom node the above `maintainAspectRatio` option.

I believe this can be done in Cedar b/c you get a reference to the chart's dom element in the `.show()` method. If the `responsive` option is truthy, you could add a debounced window resize event listener to call a new `resize()` method which would update the chart's width/height overrides based on the dom element's size and call update() [just as in the example](https://github.com/Esri/cedar/blob/master/site/source/pages/examples/responsive-example.hbs#L59-L73) only instead of setting all the overrides, you'd only update the `width` and `height` overrides.

Thoughts?

**Comment by ajturner** [comment]
Yep - I think Cedar should listen to the div resize event and handle the chart resizing. Additionally we may need to add some logic for labels depending on div size and label length. At a certain point we need to remove labels entirely.

**Comment by tomwayson** [comment]
Since I first suggested this I've had a an incident where Chart.js' responsive implementation didn't work as I expected and I ended up having to mange the responsive resizing of the charts on my own (instead of relying on their built-in `responsive: true`). That's made me realize that there may be limited benefit to including the logic internal to the library other than saving some users from having to know about debounce.

That said, if you still want to include a naive implementation that will cover most people's use cases, then I can do that.

**Comment by ajturner** [comment]
To summarize, we don't plan to add this to the library at this point. It's very easy for the app to add this now with the pending PR for simple resize.

**Comment by ajturner** [comment]
@tomwayson is this good for now and close able?

**Comment by tomwayson** [comment]
yup
