### ISSUE TITLE
Simplify Cedar API to appear like 'normal' chart library

### ISSUE THREAD

**Issue by ajturner** [Esri/cedar#95]
As a Developer, when using the Cedar API, I want it to look like a normal chart library. 

While Vega is available for completely custom chart declarations - for standard charts, provide a simple interface for declaratively constructing charts. 

All charts have the common elements

- Type: either a standard: bar, line, horizontal, scatter, bubble, pie - or a custom JSON chart
- Axes: `x`, `y`, `size`, `color`. Extensible for `row`, `col`
- Parameters: each input can be a variable field or fixed value (e.g. color based on attribute or `#55eeff`)

There are two major options - Functional method chaining, or JSON configuration. 

## Option 1: Functional chaining

ala D3

```javascript
var chart = Cedar::Chart.new()

// Make a Scatterplot chart
chart.type("scatter")
	.data([{"students": 45, "teachers": 13, "facility": "elementary"},{"students": 20, "teachers": 5, "facility": "elementary"},{"students": 87, "teachers": 20, "facility": "middle"}])
	.x({"field": "students"})
	.y({"field": "teachers"})
chart.show()

// Customize the chart
chart.legend({"visible": true})
chart.height(10).width(20)
chart.labels({"visible": true, "layout": "auto"})
chart.renderer("svg")
chart.element("#chart")

// Color by value
chart.color({"value": "red"})
// Color by field attribute
chart.color({"field": "facility"})

chart.size // => default {"value": 12}

// Customize axis labels
chart.axes({"x": {"labels": {"fontSize": 14 }}})
chart.axes({"x": {"labels": {"fill": "red" }}})

// Customize axis ticks
chart.axes({"x": {"values": ["10","50","100"]}})
chart.axes({"x": {"ticks": {"stroke": {"value": "#888"}}}})

// Add a grid
chart.axes({"y": {"grid": true}})

// Remove an axis
chart.axes({"y": false})


// Add a tooltip
chart.tooltip({"title": "A ${facility} school", "content": "${teachers} Teachers have ${students} Students"}

// Remove the tooltip
chart.tooltip(false)

// Add data
// question: what if there are multiple series on the same chart?
chart.insert([{"students": 230, "teachers": 84, "facility": "high"}]).update();

// Remove data
chart.remove( function(d) { d.facility == "middle" } )

// Load data from a Map Service
chart.type("bar")
	.layer("http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Education_WebMercator/MapServer/5")
	.query({"groupByFieldsForStatistics": "FACUSE",
		"outStatistics": [{
			"statisticType": "sum", 
			"onStatisticField": "TOTAL_STUD", 
			"outStatisticFieldName": "TOTAL_STUD_SUM"
		}]
		"geometry":{"xmin": -104, "ymin": 35.6, "xmax": -94.32, "ymax": 41}
	 })
	.x({"field":"FACUSE","label":"Facility Use"})
	.y({"field":"TOTAL_STUD_SUM","label":"Total Students"})

chart.update();
```

## Option 2: JSON configuration

This is more aligned with Vega JSON documents. 

The issue has been that managing the JSON document is unwieldy for developers and a conceptual hurdle.
### Full Example

```javascript
var chart = new Cedar({ json })
```

and the json: 

```json
  "data": {  
    "url":"...",
    "query": {
      "where": "CHARTER='Y'",
      "groupByFieldsForStatistics": "FACUSE",
      "outStatistics": {
        "statisticType": "sum",
        "onStatisticField": "TOTAL_STUD", 
        "outStatisticFieldName": "TOTAL_STUD_SUM"
      },
      "geometry":{"xmin": -104, "ymin": 35.6, "xmax": -94.32, "ymax": 41},
    },
  },
  "tooltip": {
    "title": null,
    "content": "${ZIP_CODE} has ${TOTAL_STUD} Students"
  },
  "style": {
    "type": "bar",
    "x": {"name":"ZIP_CODE", "label":"ZIP Code", "sort": [{"name": "ZIP_CODE"}]},
    "y": {"name":"TOTAL_STUD", "label":"Total Students"},
    "size": {"value": 5},
    "color": {"value": "#5ef"}
  },
  "config": { 
    "height": 200,
    "width": 850
  }
});
```

### Simplified Query

the Feature Layer API can be aBitVerbose and I would like to suggest a simplified API here, but perhaps that can be a future feature:

```json
var chart = new Cedar({
  "data": {  
    "url":"...",
    "group": "FACUSE",
    "statistics": [{"type": "sum", "field": "TOTAL_STUD"}],
    "query": {
      "where": "CHARTER='Y'",
      "geometry":{"xmin": -104, "ymin": 35.6, "xmax": -94.32, "ymax": 41},
    },
  }
});
```

### Declarative Specification

Even using custom variables:

```json
var chart = new Cedar({
  "data": {
    "values": [ { "rating_percent": 80, "rating_rank": "green" } ]
  },
  "style": {
    "type": "http://gist.github.com/gist/thermometerChart.json",
    "angle": {"name":"rating_percent", "label":"School Rating"},
    "color": {"name": "rating_rank"}
  }
}
```
### Embedded Values

```json
var chart = new Cedar({
  "data": {  
    "values": [ 
         { "ZIP_CODE": "20002", "TOTAL_STUD": 5000},
         { "ZIP_CODE": "20001", "TOTAL_STUD": 3080},
         { "ZIP_CODE": "20003", "TOTAL_STUD": 760},
     ]
  }
 ...
```

or 

```javascript
chart.data = {  
    "values": [ 
         { "ZIP_CODE": "20002", "TOTAL_STUD": 5000},
         { "ZIP_CODE": "20001", "TOTAL_STUD": 3080},
         { "ZIP_CODE": "20003", "TOTAL_STUD": 760},
     ]
  }
```

**Comment by abakirov** [comment]
Hi Andrew, 
I would add a couple of things, if it's not too difficult to include:
- In addition to chart types listed above, please support these: histogram, stacked bar, stacked horizontal, grouped bar, grouped horizontal (with *histogram* being the highest priority of these additional chart types)
- Bar, Horizontal and Pie chart should probably all have identical `inputs` as they are interchangeable in most cases. This is currently not the case: Pie chart inputs differ from Bar.

What do you think?

cc @phlorah for input as well

**Comment by ajturner** [comment]
Thanks - indeed we could keep extending with new types and will prioritized Histograms.

For Pie, first likely would suggest `angle = x` and `radius = y`

Any other high level API feedback?

**Comment by phlorah** [comment]
@ajturner wouldn't it be the other way around with the angle corresponding to the value or y axis?

**Comment by abakirov** [comment]
How about using `dimension` and `measure` for all: bar, horizontal bar and pie.

**Comment by ajturner** [comment]
@HeikoH @codylawson @dbouwman @benheb 

I would be curious about your thoughts on the updated API suggestion above that uses method chaining. 

So instead of a JSON configuration document, the JS interface would be method based - while internally it would still be constructing / manipulating the Vega JSON document.

Functionally it's not a dramatic change from the current API - but I'm hoping it makes Cedar more "approachable" for new devs.

**Comment by benheb** [comment]
As in Option 1? I like it, but I also like d3.

**Comment by ajturner** [comment]
@benheb so you like it b/c I wrote the letters `D3` above it? any other evaluation criteria? :)

**Comment by benheb** [comment]
I like it because I like method chaining and that example looked very d3-e. Not that method chaining is unique to d3, but more the extent to which it is. I also haven't had a ton of time to process this as I just now am seeing this issue.

**Comment by HeikoH** [comment]
Not sure I like the method chaining as suggested here, it's looks like a weird mix of configuration and method chaining. In the end you will still be setting parameters through JSON objects. It will also be harder to rehydrate a chart from some config object.

**Comment by codylawson** [comment]
I came from dojox/charting and c3js, so I prefer JSON configuration. I think it's a little easier to read and presents a clear hierarchy of properties. I also like it for showing all the possible/available properties for styling and other config stuffs. I think the structured approach of JSON is a benefit, over the more freeform chaining, for new developers. Having those guidelines helps IMO.

Again, most of my experience is dojo and c3, so it could just be personal preference. But JSON config makes the most sense to me.

**Comment by benheb** [comment]
Yep, not sure if I have a real preference either way, as I said mostly just drawn toward the method chaining because of the d3 look. It may in this case, as @HeikoH pointed out, be a weird mix considering other configuration options Cedar has. Also like JSON configs (I originally implemented c3 in OpenData), so that'd work too.

**Comment by ajturner** [comment]
Ok, sounds like the JSON config is preferable. So option #2 is very similar to what is there today - which looks like this for creating a Bar chart. People on this thread wouldn't change the overall structure below? (my suggestions in the description change a few key names such as `mappings` becomes `style`).

```javascript
var chart = new Cedar({
  "type": "bar",
  "dataset": {
    "url":"http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Education_WebMercator/MapServer/5",
    "query": {
      "groupByFieldsForStatistics": "FACUSE",
      "outStatistics": [{
        "statisticType": "sum", 
        "onStatisticField": "TOTAL_STUD", 
        "outStatisticFieldName": "TOTAL_STUD_SUM"
      }]
    },
    "mappings":{
      "sort": "TOTAL_STUD_SUM DESC",
      "x": {"field":"FACUSE","label":"Facility Use"},
      "y": {"field":"TOTAL_STUD_SUM","label":"Total Students"}
    }
  },
  "tooltip": {
    "id": "tooltip-url",
    "title": "{FACUSE}",
    "content": "{TOTAL_STUD_SUM} Students in {FACUSE}"
  }
});

  //show the chart
  chart.show({
    elementId: "#chart-url",
    autolabels: true
  });
```

If so, then I'll just focus instead on documentation of the current API rather than changing to method chaining.

That said - method chaining could still come in a later version.

**Comment by dbouwman** [comment]
Gah - somehow did not hit "comment" on this yesterday... but it's in-line with the other comments:

My gut feeling is that a "chained" api is no less opaque to users than a json format - unless - we copy some existing charting api, and simply "back" it with vega. 

The bottom line is that building a simple api for simple charts is simple. Having that seamlessly extend to complex charts with complex interactions is difficult. Building a complex chart using any library, d3, c3, highcharts, whatever, requires reading a lot of docs, and some experimentation, so lets take the long view, that vega will give us "more" and focus on documentation & examples.
